services:
  - type: web
    name: madewithwords-segmentation
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn -b 0.0.0.0:$PORT app:app
